import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Header } from "./components/header";
import { ProductsList } from "./components/products-list";

const monteserrat = Montserrat({
  weight: ['300', '400', '500', '600'],
  subsets: ["latin"] 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={monteserrat.className}>
        <Header/>
          {children}
          <ProductsList />
        </body>
    </html>
  );
}
